### ISSUE TITLE
Iterator ordering

### ISSUE THREAD

**Issue by mgrutten** [jchambers/jvptree#12]
Hi Jon.   I'd like to use the tree to find the elements of a collection that are spatially close to each other, rather than look for nearest neighbours of some other point.  Can I use the iterator for that?  For example, if I extract the contents of the tree into a list (as you do in the test code), is there any guarantee that points that are spatially close will be adjacent in the list?

**Comment by jchambers** [comment]
In short, no. The order of elements in an iterator is undefined.

It sounds like you're ultimately looking for clustering, which is beyond the scope of this project. That said, you might be interested in something like [OPTICS](https://en.wikipedia.org/wiki/OPTICS_algorithm).
